language: go

go:
  - 1.6

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get golang.org/x/tools/cmd/cover

install:
  - go get -v github.com/govend/govend
  - govend -v

# The default script is go test -v ./... which will test everything in the vendor directory.
# Only testing this project.
script:
  - go test -coverprofile=coverage.txt -covermode=atomic -short .

after_success:
  - bash <(curl -s https://codecov.io/bash)
